### ISSUE TITLE
no bar 

### ISSUE THREAD

**Issue by toonverm** [ip1981/YOSO#3]
Hi I'm on ubuntu 14 but I don't have your bar to open a folder. How do I solve this?

**Comment by ip1981** [comment]
See https://github.com/ip1981/YOSO/pull/2. I believe there is a bug in Ubuntu (Unity?) and there must be a workaround, per-app or global configuration options.

**Comment by ip1981** [comment]
Ok, anyway. I value native menus less then Ubuntu :) https://github.com/ip1981/YOSO/commit/674a8d128b6390e8324803960567c5d74fa39544

And this thing is written in Python on purpose ;)
